title: Pandanautinspace
description: And this is Kenneth Browder's website.
google_analytics: 
show_downloads: false
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

gems:
  - jekyll-mentions

